networks:
  infra_default:
    external: true

services:
  reth:
    image: ghcr.io/paradigmxyz/reth
    container_name: reth-el
    restart: unless-stopped
    ports:
      - "30303:30303" # eth/66 peering
      - "8545:8545" # HTTP-RPC Port
      - "8546:8546" # WebSocket-RPC Port
      - "8551:8551" # engine
    volumes:
      - ./data:/root/.local/share/reth
    # pid: host
    command: >
      node
      --chain mainnet
      --http --http.addr 0.0.0.0 --http.port 8545 --http.api "eth,net,web3"
      --ws --ws.addr=0.0.0.0 --ws.port 8546 --ws.api "eth,net,web3"
    networks:
      - infra_default 