services:
  lighthouse:
    # restart: unless-stopped
    container_name: lighthouse
    image: sigp/lighthouse:v7.0.1
    # depends_on:
    #   - reth
    ports:
      - "5052:5052/tcp" # rpc
      - "5053:5053/tcp"
      - "5054:5054/tcp" # metrics
      - "9000:9000/tcp" # p2p
      - "9000:9000/udp" # p2p
    volumes:
      - ./data:/root/.lighthouse
      - ../reth/data/mainnet/jwt.hex:/root/jwt.hex:ro
    command: >
      lighthouse bn
      --network mainnet
      --http --http-address 0.0.0.0
      --execution-endpoint http://reth:8551
      --execution-jwt /root/jwt.hex
      --checkpoint-sync-url https://sync-mainnet.beaconcha.in
      --checkpoint-sync-url-timeout=300
    networks:
      - infra_default 

networks:
  infra_default:
    external: true
